-- ============================================================================
-- 039_ledger_immutability_phase2b.sql
-- Phase 2B of the ledger-immutability rollout. Attaches the existing
-- tg_block_ledger_mutation() function (mig 037) as BEFORE UPDATE OR DELETE
-- triggers on the legacy settlements engine tables:
--
--   * public.settlements         (mig 002)
--   * public.settlement_items    (mig 002)
--
-- Why both tables are safe to lock now
-- ────────────────────────────────────
-- Per the PR2B audit, the entire mutation surface against these two tables
-- consists of two SECURITY DEFINER RPCs in mig 017 (staging gate confirmed:
-- prosecdef = true; owner is the migration runner role, NOT service_role):
--
--   * generate_lab_settlement_admin(uuid, date, date, user_role, uuid, text)
--       INSERT settlements          (one row, defaults rest)
--       INSERT settlement_items     (N rows, bulk)
--       UPDATE settlements          (rollup of total_orders + total_lab_amount)
--       — all three statements run inside the same RPC body and the same
--         transaction. The trigger does not fire on INSERT; the rollup
--         UPDATE runs with current_user = function owner, NOT service_role,
--         so the trigger allows it.
--
--   * set_settlement_status_admin(uuid, settlement_status, numeric)
--       UPDATE settlements          (status, total_paid, updated_at)
--       — same security context; allowed.
--
-- settlement_items has zero UPDATE/DELETE callers anywhere in the codebase
-- (verified in src/, scripts/, supabase/migrations/). Locking it is purely
-- a guardrail against future drift, identical in shape to the Phase-1
-- INSERT-only tables.
--
-- Out of scope (legacy-engine fragility, NOT an immutability concern):
--   * Duplicate-settlement creation: no unique constraint on
--     (lab_id, period_start, period_end). Pre-existing.
--   * Eligibility filter bug: the literal 'results_uploaded' in
--     generate_lab_settlement_admin does not match the canonical
--     order_status enum value 'result_ready' (mig 023). Pre-existing.
--   * Dead settlement_items.status flow: the column defaults to 'pending'
--     and is never updated by any code path today. Pre-existing.
-- These three items are tracked separately and must NOT be folded into
-- the immutability work.
--
-- Idempotency
-- ───────────
-- drop trigger if exists … + create trigger. Re-applying is a no-op.
-- The function tg_block_ledger_mutation() is created (or replaced) by
-- mig 037 and reused here unchanged.
--
-- Rollback
-- ────────
-- A new numbered migration drops the two triggers:
--
--   drop trigger if exists trg_lock_settlements      on public.settlements;
--   drop trigger if exists trg_lock_settlement_items on public.settlement_items;
--
-- The function may stay; Phase 1 and PR2A still reference it.
-- Per the project's migration-ordering invariant, do NOT edit this file
-- in place to revert — ship a new numbered migration that supersedes it.
-- ============================================================================

do $$ begin
  drop trigger if exists trg_lock_settlements on public.settlements;
  create trigger trg_lock_settlements
    before update or delete on public.settlements
    for each row execute function public.tg_block_ledger_mutation();
end $$;

do $$ begin
  drop trigger if exists trg_lock_settlement_items on public.settlement_items;
  create trigger trg_lock_settlement_items
    before update or delete on public.settlement_items
    for each row execute function public.tg_block_ledger_mutation();
end $$;
